-- Snowflake worksheet-ல் ஒரு முறை மட்டும் run செய்யவும்
-- Layers: RAW (அப்படியே data) -> CLEAN (சுத்தம்) -> FINAL (report) + AUDIT (logs)

CREATE WAREHOUSE IF NOT EXISTS ETL_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS ETL_DB;
CREATE SCHEMA IF NOT EXISTS ETL_DB.RAW;
CREATE SCHEMA IF NOT EXISTS ETL_DB.CLEAN;
CREATE SCHEMA IF NOT EXISTS ETL_DB.FINAL;
CREATE SCHEMA IF NOT EXISTS ETL_DB.AUDIT;

-- RAW: எல்லாம் STRING, source-ல் வந்தபடியே சேமிப்போம்
CREATE TABLE IF NOT EXISTS ETL_DB.RAW.EMPLOYEES_RAW (
  EMP_ID      STRING,
  FIRST_NAME  STRING,
  LAST_NAME   STRING,
  DEPARTMENT  STRING,
  SALARY      STRING,
  HIRE_DATE   STRING,
  SOURCE_FILE STRING,
  BATCH_ID    STRING,
  LOAD_TS     TIMESTAMP_NTZ
);

-- AUDIT: pipeline ஒவ்வொரு படியிலும் என்ன நடந்தது என்ற பதிவு
CREATE TABLE IF NOT EXISTS ETL_DB.AUDIT.PIPELINE_LOG (
  BATCH_ID STRING,
  STEP     STRING,
  STATUS   STRING,
  DETAIL   STRING,
  LOG_TS   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
